server:
  port: 8000

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password:
    timeout: 5000
    pool:
      max-active: 50
      min-idle: 20
      max-idle: 10
      max-wait: 1000




